version: "3.7"
services:
  mailer:
    image: jeanberu/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      services-net:
        ipv4_address: 172.16.239.1

  emqx:
    image: emqx/emqx:latest
    ports:
      - "18083:18083"
      - "8083:8083"
      - "8084:8084"
    networks:
      services-net:
        ipv4_address: 172.16.239.2

  iot_database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "iot"
      MYSQL_USER: "cesi"
      MYSQL_PASSWORD: "cesi_pwd"
    volumes:
      - "/srv/iot_db:/var/lib/mysql"
    ports:
      - "7327:3306"
    networks:
      services-net:
        ipv4_address: 172.16.239.3

  calculations_database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "calculations"
      MYSQL_USER: "cesi"
      MYSQL_PASSWORD: "cesi_pwd"
    volumes:
      - "/srv/calculations_db:/var/lib/mysql"
    ports:
      - "7328:3306"
    networks:
      services-net:
        ipv4_address: 172.16.239.4

networks:
  services-net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.239.0/24"