version: "3.7"
services:
  metric_persistence:
    build:
      context: ./src/Services/MetricPersistence
      dockerfile: Dockerfile.dev

  calculation_engine:
    build:
      context: ./src/Services/Calculation/Calculation.Engine
      dockerfile: Dockerfile.dev

  device_api:
    build:
      context: ./src/Services/Device/Device.API
      dockerfile: Dockerfile.dev

  calculation_api:
    build:
      context: ./src/Services/Calculation/Calculation.API
      dockerfile: Dockerfile.dev

  mobile_api:
    build:
      context: ./src/Services/Mobile.API
      dockerfile: Dockerfile.dev

  web_admin:
    build:
      context: ./src/Web/Admin
      dockerfile: Dockerfile.dev