FROM microsoft/dotnet:2.2.104-sdk-alpine AS build
WORKDIR /src/Services/Calculation/Calculation.Engine
COPY *.csproj ./
RUN dotnet restore
COPY . ./
RUN dotnet build -c Release -o out

FROM build AS publish
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:2.2.2-aspnetcore-runtime-alpine AS runtime
WORKDIR /src/Services/Calculation/Calculation.Engine
COPY --from=publish /src/Services/Calculation/Calculation.Engine/out .
ENTRYPOINT ["dotnet", "Calculation.Engine.dll"]